// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEUNrHdVaFhAlasISFdQmKZiXyuuwuvXQ',
    appId: '1:850087823328:web:b1121b3b31b0b4d0758d85',
    messagingSenderId: '850087823328',
    projectId: 'utdpickup',
    authDomain: 'utdpickup.firebaseapp.com',
    storageBucket: 'utdpickup.appspot.com',
    measurementId: 'G-4R411QVLZ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQL-lqTgbOQhTv8F1Oj1YGsqlDCTb-Za8',
    appId: '1:850087823328:android:49aae45eba0d0b47758d85',
    messagingSenderId: '850087823328',
    projectId: 'utdpickup',
    storageBucket: 'utdpickup.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQoWgOf3ztKcbAAiFti0JGZZWRhGSJ2zw',
    appId: '1:850087823328:ios:76d563a95ce7bb90758d85',
    messagingSenderId: '850087823328',
    projectId: 'utdpickup',
    storageBucket: 'utdpickup.appspot.com',
    iosBundleId: 'com.example.pickup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQoWgOf3ztKcbAAiFti0JGZZWRhGSJ2zw',
    appId: '1:850087823328:ios:069c3dbf68800377758d85',
    messagingSenderId: '850087823328',
    projectId: 'utdpickup',
    storageBucket: 'utdpickup.appspot.com',
    iosBundleId: 'com.example.pickup.RunnerTests',
  );
}
